In [9]:
import pandas as pd
import joblib

In [ ]:
df = joblib.load(
    r'C:\Users\Gauri\Parakh-task-5\model_training\skill_gap_analysis.ipynb')
career_results_df.head()

KeyError: 123

In [13]:
print(df.columns.tolist())

NameError: name 'df' is not defined

In [ ]:
print(df.shape)

(1399, 44)

In [ ]:
print(df.dtypes)

experience_years                   int64
python                             int64
java                               int64
c_cpp                              int64
javascript                         int64
typescript                         int64
html_css                           int64
react                              int64
angular_vue                        int64
nodejs                             int64
fastapi_flask                      int64
django                             int64
sql                                int64
nosql                              int64
mongodb                            int64
postgresql                         int64
pandas_numpy                       int64
scikit_learn                       int64
deep_learning                      int64
pytorch_tensorflow                 int64
nlp                                int64
computer_vision                    int64
docker                             int64
kubernetes                         int64
git                                int64
linux                              int64
aws                                int64
azure_gcp                          int64
ci_cd                              int64
terraform                          int64
cybersecurity_basics               int64
penetration_testing                int64
flutter_react_native               int64
target_career                     object
total_skills                       int64
ml_skill_count                     int64
web_skill_count                    int64
experience_skill_score             int64
education_level_B.Tech / B.E.    float64
education_level_BCA              float64
education_level_M.Tech / MCA     float64
education_level_Self-Taught      float64
programming_score                  int64
data_skill_score                   int64
dtype: object

In [ ]:
career_skills = {
    "Data Scientist": [
        "Python",
        "SQL",
        "Statistics",
        "Machine Learning",
        "Pandas",
        "NumPy"
    ],

    "ML Engineer": [
        "Python",
        "Machine Learning",
        "Statistics",
        "SQL",
        "Deep Learning",
        "Model Deployment"
    ],

    "Data Analyst": [
        "Python",
        "SQL",
        "Statistics",
        "Excel",
        "Pandas",
        "Data Visualization"
    ],

    "Software Developer": [
        "Python",
        "Programming",
        "Data Structures",
        "Algorithms",
        "Git"
    ],

    "Web Developer": [
        "HTML",
        "CSS",
        "JavaScript",
        "React",
        "Git"
    ]
}

In [ ]:
student_skills = [
    "Python",
    "SQL",
    "Machine Learning",
    "Pandas"
]

In [ ]:
print(student_skills)

['Python', 'SQL', 'Machine Learning', 'Pandas']

In [ ]:
target_career = "ML Engineer"
required_skills = career_skills[target_career]
missing_skills = [
    skill for skill in required_skills
    if skill not in student_skills
]
available_skills = [
    skill for skill in required_skills
    if skill in student_skills
]
print("Career:", target_career)
print("\nSkills You Have:")
print(available_skills)
print("\nMissing Skills:")
print(missing_skills)

Career: ML Engineer

Skills You Have:
['Python', 'Machine Learning', 'SQL']

Missing Skills:
['Statistics', 'Deep Learning', 'Model Deployment']

In [ ]:
match_score = (
    len(available_skills) /len(required_skills)) * 100
print("Career:", target_career)
print("Match Score:", round(match_score, 2), "%")

Career: ML Engineer
Match Score: 50.0 %

In [ ]:
def skill_gap_analysis(student_skills, target_career):
    required_skills = career_skills[target_career]
    available_skills = [
        skill for skill in required_skills
        if skill in student_skills]
    missing_skills = [
        skill for skill in required_skills
        if skill not in student_skills]
        
    match_score = (
        len(available_skills) /
        len(required_skills)
    ) * 100

    return {
        "career": target_career,
        "available_skills": available_skills,
        "missing_skills": missing_skills,
        "match_score": round(match_score, 2)
    }

In [ ]:
result = skill_gap_analysis(
    student_skills,
    "ML Engineer"
)

print(result)

{'career': 'ML Engineer', 'available_skills': ['Python', 'Machine Learning', 'SQL'], 'missing_skills': ['Statistics', 'Deep Learning', 'Model Deployment'], 'match_score': 50.0}

In [ ]:
print("Career:", result["career"])
print("Match Score:", result["match_score"], "%")

print("\nAvailable Skills:")
for skill in result["available_skills"]:
    print("✓", skill)

print("\nMissing Skills:")
for skill in result["missing_skills"]:
    print("✗", skill)

Career: ML Engineer
Match Score: 50.0 %

Available Skills:
✓ Python
✓ Machine Learning
✓ SQL

Missing Skills:
✗ Statistics
✗ Deep Learning
✗ Model Deployment

In [ ]:
career_results = []

for career in career_skills:
    result = skill_gap_analysis(
        student_skills,
        career
    )
    career_results.append(result)

In [ ]:
career_results = []
for career in career_skills:
    result = skill_gap_analysis(student_skills,career)
    career_results.append(result)

In [ ]:
career_results_df = pd.DataFrame(career_results)
career_results_df

,career,available_skills,missing_skills,match_score
0,Data Scientist,"[Python, SQL, Machine Learning, Pandas]","[Statistics, NumPy]",66.67
1,ML Engineer,"[Python, Machine Learning, SQL]","[Statistics, Deep Learning, Model Deployment]",50.00
2,Data Analyst,"[Python, SQL, Pandas]","[Statistics, Excel, Data Visualization]",50.00
3,Software Developer,[Python],"[Programming, Data Structures, Algorithms, Git]",20.00
4,Web Developer,[],"[HTML, CSS, JavaScript, React, Git]",0.00

In [ ]:
career_results_df = career_results_df.sort_values(by="match_score",ascending=False)
career_results_df

,career,available_skills,missing_skills,match_score
0,Data Scientist,"[Python, SQL, Machine Learning, Pandas]","[Statistics, NumPy]",66.67
1,ML Engineer,"[Python, Machine Learning, SQL]","[Statistics, Deep Learning, Model Deployment]",50.00
2,Data Analyst,"[Python, SQL, Pandas]","[Statistics, Excel, Data Visualization]",50.00
3,Software Developer,[Python],"[Programming, Data Structures, Algorithms, Git]",20.00
4,Web Developer,[],"[HTML, CSS, JavaScript, React, Git]",0.00

In [ ]:
top_careers = career_results_df.head(3)
top_careers

,career,available_skills,missing_skills,match_score
0,Data Scientist,"[Python, SQL, Machine Learning, Pandas]","[Statistics, NumPy]",66.67
1,ML Engineer,"[Python, Machine Learning, SQL]","[Statistics, Deep Learning, Model Deployment]",50.00
2,Data Analyst,"[Python, SQL, Pandas]","[Statistics, Excel, Data Visualization]",50.00

In [ ]:
print("Recommended Careers\n")
for i, row in top_careers.iterrows():
    print(
        row["career"],
        "->",
        row["match_score"],
        "%"
    )

Recommended Careers

Data Scientist -> 66.67 %
ML Engineer -> 50.0 %
Data Analyst -> 50.0 %

In [ ]:
top_career = career_results_df.iloc[0]
print("Recommended Career:")
print(top_career["career"])
print("\nMatch Score:")
print(top_career["match_score"], "%")
print("\nMissing Skills:")

for skill in top_career["missing_skills"]:
    print("•", skill)

Recommended Career:
Data Scientist

Match Score:
66.67 %

Missing Skills:
• Statistics
• NumPy

In [ ]:
def career_recommendation(student_skills):
    results = []
    for career in career_skills:
        required_skills = career_skills[career]
        available_skills = [
            skill for skill in required_skills
            if skill in student_skills
        ]
        missing_skills = [
            skill for skill in required_skills
            if skill not in student_skills
        ]
        match_score = (
            len(available_skills) / len(required_skills)) * 100

        results.append({
            "career": career,
            "match_score": round(match_score, 2),
            "available_skills": available_skills,
            "missing_skills": missing_skills
        })

    results_df = pd.DataFrame(results)
    results_df = results_df.sort_values(
        by="match_score",
        ascending=False).reset_index(drop=True)
    return results_df

In [ ]:
recommendations = career_recommendation(student_skills)

recommendations

NameError: name 'career_skills' is not defined